// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoI_xQ64PATNKxWGg8QkhWNBOeI-FLlFk',
    appId: '1:20519415065:web:7924042806b87b12352988',
    messagingSenderId: '20519415065',
    projectId: 'dpei-project',
    authDomain: 'dpei-project.firebaseapp.com',
    storageBucket: 'dpei-project.firebasestorage.app',
    measurementId: 'G-ZE5DEHPBEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoe5IKYURNS92h7AevH5nXbcGa2WareHI',
    appId: '1:20519415065:android:15ddf9a055504ac4352988',
    messagingSenderId: '20519415065',
    projectId: 'dpei-project',
    storageBucket: 'dpei-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiDbLS5QAeANHXgsa5N0cegrJGlpRLhs4',
    appId: '1:20519415065:ios:166e3d1b0f61479b352988',
    messagingSenderId: '20519415065',
    projectId: 'dpei-project',
    storageBucket: 'dpei-project.firebasestorage.app',
    iosBundleId: 'com.example.dpeiProject',
  );
}
